version: '3'
services:
  db:
    container_name: post_proc_db
    image: percona
    volumes:
      - ../scripts:/scripts
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    container_name: post_proc_db_admin
    image: adminer
    restart: always
    ports:
      - 8081:8080
    links:
      - db
  post-proc:
    container_name: post_proc_restapi
    build: ../build
    volumes:
      - ../.:/go/src/github.com/olivernadj/post-proc
    working_dir: /go/src/github.com/olivernadj/post-proc/cmd/restapi
    ports:
      - 8080:8080
    command: "go run main.go"
    links:
      - db
