version: '3'
services:
  db:
    image: percona
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    links:
      - db
  post-proc:
    build: ../build
    volumes:
      - ../.:/go/src/github.com/olivernadj/post-proc
    working_dir: /go/src/github.com/olivernadj/post-proc/cmd/post-proc
    ports:
      - 8080:8080
    command: "go run main.go"
    links:
      - db
