version: '3'
services:
  db:
    container_name: post_proc_db
    image: percona
    volumes:
      - ../scripts:/scripts
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    container_name: post_proc_db_admin
    image: adminer
    ports:
      - 8081:8080
    links:
      - db
  db-metrics:
    container_name: post_proc_db_metrics
    image: prom/mysqld-exporter
    environment:
      DATA_SOURCE_NAME: "root:example@(db:3306)/"
    ports:
      - 9104:9104
    links:
      - db
  restapi:
    container_name: post_proc_restapi
    build: ../build/restapi
    volumes:
      - ../.:/go/src/github.com/olivernadj/post-proc
    working_dir: /go/src/github.com/olivernadj/post-proc/cmd/restapi
    environment:
      DATA_SOURCE_NAME: "root:example@tcp(db:3306)/postproc?parseTime=true"
    ports:
      - 8080:8080
    command: "go run main.go"
    links:
      - db
  statemachine:
    container_name: post_proc_statemachine
    build: ../build/statemachine
    volumes:
      - ../.:/go/src/github.com/olivernadj/post-proc
    working_dir: /go/src/github.com/olivernadj/post-proc/cmd/statemachine
    environment:
      DATA_SOURCE_NAME: "root:example@tcp(db:3306)/postproc?parseTime=true"
    ports:
      - 8082:8082
    command: "go run main.go"
    links:
      - db
  prometheus:
    build: ../build/prometheus
    volumes:
      - /prometheus
    ports:
      - "9090:9090"
    links:
      - db-metrics
      - restapi
      - statemachine
  grafana:
    image: grafana/grafana:6.0.2
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 5ecret
    volumes:
      - ../build/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    user: "1000"
    links:
      - prometheus
