version: '3'
services:
  db:
    image: percona
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    links:
      - db
  postapi:
    build: ./goapi
    volumes:
      - ./goapi:/go/src/goapi
    working_dir: /go/src/goapi
    ports:
      - 8080:8080
    command: "go run main.go"
    links:
      - db
