/*
 * Post process
 *
 * This is a sample server Processing and saving incoming requests
 *
 * API version: 1.0.0
 * Contact: mr.oliver.nadj@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"net/http"
)

func AddAction(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
