/*
 * Post process
 *
 * This is a sample server Processing and saving incoming requests
 *
 * API version: 1.0.0
 * Contact: mr.oliver.nadj@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"encoding/json"
	"github.com/olivernadj/post-proc/pkg/model"
	"log"
	"net/http"
)

func AddAction(w http.ResponseWriter, r *http.Request) {
	var req model.Action
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		log.Printf("cannot parse request: %v\n", err)
		w.WriteHeader(http.StatusBadRequest)
		return
	}

	req.SourceType = r.Header.Get("Source-Type")
	err := req.Insert()
	if err != nil {
		log.Printf(err.Error())
		w.WriteHeader(http.StatusInternalServerError)
		return
	}

	w.WriteHeader(http.StatusCreated)
}
