/*
 * Post process
 *
 * This is a sample server Processing and saving incoming requests
 *
 * API version: 1.0.0
 * Contact: mr.oliver.nadj@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"github.com/olivernadj/post-proc/internal/api"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	router.NotFoundHandler = http.FileServer(http.Dir("../../web/swaggerui/"))
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("Action API"))
}

var routes = Routes{
	Route{
		"Swagger",
		"GET",
		"/v1/",
		Index,
	},

	Route{
		"AddAction",
		strings.ToUpper("Post"),
		"/v1/action",
		swagger.AddAction,
	},
}
